### ISSUE TITLE
Can lsst.sims be really replaced by rubin_sim?

### ISSUE THREAD

**Issue by deltasata** [lsst/rubin_sim#350]
I am new and trying to use OpSimSummary that needs `lsst.sims.maf`. 
As advised at https://confluence.lsstcorp.org/display/SIM/Catalogs+and+MAF,
I tried to use `rubin_sim` and by replacing `lsst.sims` with `rubin_sim`. 
This works: `from lsst.sims.maf import db` --> `from rubin_sim.maf import db` 
but this does not: `from lsst.sims.maf.utils import opsimUtils` --> `from rubin_sim.maf.utils import opsimUtils` .
Got this error: `ImportError: cannot import name 'opsimUtils' from 'rubin_sim.maf.utils'`
Also got this error later on: `AttributeError: module 'rubin_sim.maf.db' has no attribute 'OpsimDatabase'`

I don't have lsst sim installed, neither I want to do that.
Please help., thank you.

**Comment by tribeiro** [comment]
Sorry, I don't think we kept a list of the things that were renamed. Mostly because we had to rename a lot of things. 

You can check the package [API docs](https://rubin-sim.lsst.io/rubin_sim/index.html#rubin-sim-maf-api) though, and see if you find what you are looking for. If you provide a list of the packages you are trying to import I can check them for you.

**Comment by rhiannonlynne** [comment]
Like @tribeiro said - there were a lot of things which were renamed, and some things even disappeared. 
In general, I wouldn't expect you to need to import opsim_utils and we removed the OpsimDatabase class entirely (because it's just a sqlite file only now, without the extra items we had in place in OpsimDatabase). 
It might be helpful to look at some of our newer tutorials here - https://github.com/lsst/rubin_sim_notebooks/tree/main/maf/tutorial - which you could probably just buzz through really quickly to look at how things work now compared to how you're expecting based on the old notebook (I would kind of think you could look and say "yes, that's what I'm doing here .. let me copy/paste the new code instead). 
You may also find the notebooks here - https://github.com/lsst/rubin_sim_notebooks/tree/main/maf/science - useful in places, to see some uses of new metrics with rubin_sim.
