### ISSUE TITLE
Getting NaN's in solar magnitudes.

### ISSUE THREAD

**Issue by rmjarvis** [lsst/rubin_sim#370]
In some cases, we are getting NaNs in sky_model spectra.

Here is a test script that reproduces the error, at least on USDF and other linux machines.  (It seems to pass on Macs, at least in one case.)
```
import numpy as np
from rubin_sim import skybrightness
sky_model = skybrightness.SkyModel()

ra, dec = 60.49055482066166, -38.16437996317624
mjd = 60143.421569611106

sky_model.set_ra_dec_mjd(ra, dec, mjd, degrees=True)
wave, spec = sky_model.return_wave_spec()

print(spec[0])
assert not any(np.isnan(spec[0]))
```
I tracked down the issue to the calculation of solar_mag for B, G, and R bands.  They come out as nan.
I believe the root problem is this snippet in `SED.resample_sed()`:
```
            if wavelen[0] > wavelen_grid[0] or wavelen[-1] < wavelen_grid[-1]:
                f = interpolate.interp1d(wavelen, flux, bounds_error=False, fill_value=numpy.NaN)
                flux_grid = f(wavelen_grid)
            else:
                flux_grid = numpy.interp(wavelen_grid, wavelen, flux)
```
Somehow wavelen_grid[-1] is coming out 1.e-10 larger than wavelen[-1], so the first branch is triggered.  Then you instruct interp1d to fill the values outside the range with NaN (!!!).  The result of this is then passed to np.trapz to compute the integral, which makes that NaN, and things propagate from there.
Filling with NaN just seems like an error.  I can't think why that would ever be the right thing to do here.  You should presumably either fill with 0 or shrink the grid to match the input wavelen array or something like that.  Putting NaNs into something you're planning to do real calculations with is asking for trouble.

**Comment by cwwalter** [comment]
Just as an informational point I personally do get the same error using weekly _39 on MacOS Intel.  (And we all see it on USDF) with latest weeklies.

**Comment by yoachim** [comment]
I've always been a little confused by the `Sed` resampling methods since they are doing interpolations where I would normally expect flux-conserving re-binning. 

Anyway, I just put in a 1-line fix that should prevent using the problem if branch.

**Comment by rhiannonlynne** [comment]
If it's helpful in terms of background, there has been some discussion about this behavior in the past -- https://community.lsst.org/t/producing-lsst-mags-from-partial-sed/6918/2
but the short answer there was Nans were more obvious to people than numbers which just happened to drop to 0.
However, I think the use of phot_utils functions in catalogs (which was a big part of the motivation toward the current behavior) is likely past, and we should shift from making things have ways to "try to be fast" and more "try to be more flexible".

**Comment by yoachim** [comment]
#375  should solve the issue of the sky model throwing NaNs (at least the example case works now). We'll probably do a deeper fix in `phot_utils` to not throw NaNs in general later.

**Comment by cwwalter** [comment]
Thanks.  Can you make a new minor release so that this gets into the weeklies?

**Comment by rhiannonlynne** [comment]
Yes, I'll do that now.

**Comment by rhiannonlynne** [comment]
OPSIM-1087 (and I am currently locked out of JIRA, so I'll put my comment here so I can add it back there later ...)

"The original plan for Sed + Bandpass in generating large catalogs in LSST bandpasses (such as the stellar catalog that used to be on Fatboy) was to 
match bandpass wavelength grids (on a tight enough sampling that photometry errors from our stellar and galaxy and AGN SEDs were minimal) for all filters; read SEDs and resample onto the same wavelength grid (after potentially redshifting galaxy or AGN seds, or adding extragalactic dust extinction), and then calculating six-color magnitudes using all filters per sed in one calculation. 
In practice now, users have arbitrary but one-off SEDs, do not use the caching capabilities in Sed, and expect the bandpass to be trimmed to a more limited wavelength region. Having SEDs which do not completely cover the bandpass range should not produce Nans, so we should fill out-of-bound data (in the case of a SED truly not overlapping the wavelength range) with 0's (or more likely, specify with kwarg whether it should be 0 or nan, and use 0 as the default). 
Because neither the wavelength grid for the SED nor the bandpass is predictable, and narrow features can exist in either, it would also be desirable to simply resample onto the tightest parts of both, so as to capture sharp features in either. "

**Comment by rhiannonlynne** [comment]
But also -- https://github.com/lsst/rubin_sim/releases/tag/1.3.3 
I'll mark this issue closed.
